languageCode = "en-us"
theme = "hugo-resume"

title = "Tess Starr"
baseURL = "https://tess-starr.com/"

[params]
address = "Plymouth, MI"
email = "tess@tess-starr.com"
favicon = "/icon/favicon.ico"
firstName = "Tess"
lastName = "Starr"
phone = ""
profileImage = "images/zion.jpg"

showEducation = true
showTeaching = false
showConferences = true
showExperience = true
showOpenSource = false
showProjects = false
showPublications = false
showQr = false
showSkills = false
showCertifications = false
showBlog = false

[[params.handles]]
link = "https://www.linkedin.com/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/Star1267"
name = "GitHub"
[[params.handles]]
link = "https://tess-starr.bandcamp.com/"
name = "bandcamp"

# Add as many as you like. So long as the name is found on this list
# https://fontawesome.com/v4/icons/#brand
# it should render a logo. For example:

# [[params.handles]]
# link = "https://mathoverflow.net/users/"
# name = "Stack-Overflow"

# This would render a stack-overflow icon linking to your page if you wanted

# ==============================================================================
# No need to change anything below here
# ==============================================================================


PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
